// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN8rCSsKYGoYJnLFqp5BKCS3Pgm5g3wk0',
    appId: '1:778328355190:web:782d122b4960e314688a57',
    messagingSenderId: '778328355190',
    projectId: 'iot-kelompok-3',
    authDomain: 'iot-kelompok-3.firebaseapp.com',
    databaseURL: 'https://iot-kelompok-3-default-rtdb.firebaseio.com',
    storageBucket: 'iot-kelompok-3.appspot.com',
    measurementId: 'G-HXQDD2QKYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvEg643hSp0U1PPCfVvb3jLofr2ZrimV8',
    appId: '1:778328355190:android:eb3cb6443da10f75688a57',
    messagingSenderId: '778328355190',
    projectId: 'iot-kelompok-3',
    databaseURL: 'https://iot-kelompok-3-default-rtdb.firebaseio.com',
    storageBucket: 'iot-kelompok-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC5N5KGK5qzw2awVVHP65a_eUX1eCuG7k',
    appId: '1:778328355190:ios:f0d8b225b25c5aa6688a57',
    messagingSenderId: '778328355190',
    projectId: 'iot-kelompok-3',
    databaseURL: 'https://iot-kelompok-3-default-rtdb.firebaseio.com',
    storageBucket: 'iot-kelompok-3.appspot.com',
    androidClientId: '778328355190-k0m09nhqvjo66db3gucb5jp18nd41drv.apps.googleusercontent.com',
    iosClientId: '778328355190-lp4pttsucn75nr7v161rnfp961grt04a.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotDht11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC5N5KGK5qzw2awVVHP65a_eUX1eCuG7k',
    appId: '1:778328355190:ios:f0d8b225b25c5aa6688a57',
    messagingSenderId: '778328355190',
    projectId: 'iot-kelompok-3',
    databaseURL: 'https://iot-kelompok-3-default-rtdb.firebaseio.com',
    storageBucket: 'iot-kelompok-3.appspot.com',
    androidClientId: '778328355190-k0m09nhqvjo66db3gucb5jp18nd41drv.apps.googleusercontent.com',
    iosClientId: '778328355190-lp4pttsucn75nr7v161rnfp961grt04a.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotDht11',
  );
}
